### ISSUE TITLE
Založení události - lokalizace události

### ISSUE THREAD

**Issue by risa** [Tomucha/coordinator#9]
Při zakládání události není úplně jasné, jak událost lokalizovat. Většina lidí buďto nepochopí vůbec, popřípadě si neuvědomí/zapomenou, že musí do mapy zadat špendlík či špendlíky, které potom události lokalizují.

Většoina událostí se díky tomu lokalizuje v Praze - Riegrovy sady, což vede k dojmu, že je to nejnebezpečnější lokality ve známém vesmíru.

Vyhledávání v mapě je také trošku nelogické - vyhledávání začíná událostí onBlur, ale pokud by tam bylo odesílací tlačítko, které se disabluje po odeslání, dokud se mapa nenačte, tak by to bylo intuitivnější. Zvláště pokud lidé sedí na pomalém připojení, kde načtení mapových podkladů může cvíli trvat, tak mají pocit že se neděje nic.

**Comment by Tomucha** [comment]
Hledání:
<head>
<title>Access blocked</title>
</head>
<body>

<h1>Access blocked</h1>

<p>You have been blocked because you have been overusing OSM's geocoding service.
Please be aware that OSM's resources are limited and shared between many users.
To have this block lifted, contact the Nominatim system administrator at
nominatim@openstreetmap.org.</p>

<p>For more information, consult the <a href="http://wiki.openstreetmap.org/wiki/Nominatim_usage_policy">usage policy</a> for the OSM Nominatim server.
</body>
</head>

Eeeeeeee, s tím toho asi moc nenadělám se obávám ...

**Comment by Tomucha** [comment]
Zadavani lokace upraveno - jednak validace, jednak preusporadani formulare. Opravena buga na editu udalosti, kde se do mapy lokace nedostaly vubec.

**Comment by Tomucha** [comment]
Zadavani lokace opraveno v 3fb4961. Dam vedet az zverejnim.

Co s tim access blocked čéče?

**Comment by risa** [comment]
To jsou request z client side nebo ze serveru?

**Comment by Tomucha** [comment]
Pta se server, takze ok, slo by to prenest na klienty, ale obavam se, ze tim problem bud odlozime, a nebo kdyz se budeme snazit, tak se nam podari s nima trochu vyjebat. Ale to bych nerad.

Ještě to můžeme ignorovat, na ostrým to zatím chodí bez problémů.

**Comment by risa** [comment]
No a nešlo by to kešovat? V ostrém provozu myslím že to zase nebude tam moc rozdílných dotazů, ne?

**Comment by Tomucha** [comment]
Přidán čudlík.

Cachovat by to šlo, ale musel bych si to rvát někam do naší DB, což bych ovšem rád považoval za víceprce.

**Comment by risa** [comment]
Tomuto přání v zásadě rozumím .. nešlo by vyzkoušet třeba tohle? http://docs.spring.io/spring/docs/3.1.0.M1/spring-framework-reference/html/cache.html 

Než aby jsi programoval nějako kešovací logiku, tak jenom dropnuot todlecto? Teda na gůůgle apendžínu jsem to ještě nepruboval, ale snad by to fungovat mohlo?
